### ISSUE TITLE
Method to set test environment values

### ISSUE THREAD

**Issue by georgecrawford** [allure-framework/allure-js-commons#10]
I'm a little confused between the `environment-variable`, implemented in https://github.com/allure-framework/allure-js-commons/issues/8, and the 'test environment values' documented in https://github.com/allure-framework/allure-core/wiki/Environment, which doesn't seem to be implemented.

Is it in scope for allure-js-commons to provide a method to create an `environment.xml` file?

**Comment by just-boris** [comment]
You're right. `<parameters>` is a bunch of related information from a test. It has to have different kinds to make different views in the report. That things have a naming with Java origins:
- **argument** - argument of parametrized test. There is no canonical way to write parametrized tests in javascript. So, in allure.js, it is just an arbitrary parameter, but it has specific view in the report. Argument hints, that you have the test with different argument in the report.
- **environment-variable** - some value used in tests, but not argument. Usually, it is the same for several tests and contains something, like test host address.
- **system-property** - very Java-specific thing, so I omited that in JS-part. You able to configure Java-tests with that abstraction. It is looks like `NODE_ENV` thing in JS, but not exactly.

Environment is a different thing, it is only single in the report. It is provided with special file `enviroment.xml` and contains all system environment from process. It can be done in allure-js-commons as well. It would be dump of all keys in the `process.env`.

We spent so many time to come up with that names, but if you have a better idea, we are open to change.

**Comment by georgecrawford** [comment]
That's fine. i think I need to use `environment-variable` then. Perhaps you could add the nice detail from above to `allure.addArgument` and `allure.addEnvironment` [here](https://github.com/allure-framework/mocha-allure-reporter/blob/master/README.md#runtime-api), as it is a bit clearer to understand.

**Comment by matlev1** [comment]
is there a way to achieve the same by using java-maven-testng-allure, I am not able to find a way to add browsers to my report.

**Comment by AutomatedOwl** [comment]
For the java case I've created a library: https://github.com/AutomatedOwl/allure-environment-writer
you're welcome to contribute
