### ISSUE TITLE
Is there a way to add Issues and/or TestCaseID through JS?

### ISSUE THREAD

**Issue by irushah** [allure-framework/allure-js-commons#13]
Hi, i am looking to add links to issues and Testcase ids in my Jasmine tests (using js). Is there a way to link them?

**Comment by just-boris** [comment]
Sure.

``` js
allure.addLabel('testId', 123);
```

As well you can also add issue ids

``` js
allure.addLabel('issue', 'ISSUE-123');
```

Then you should generate report with some properties provided

```
allure generate allure-results -Dallure.issues.tracker.pattern=%YOUR_BUGTRACKER_BASEURL% -Dallure.tests.management.pattern=%YOUR_TMS_BASEURL%
```

Sorry, that this is still not documented, but you can use it for sure.

**Comment by just-boris** [comment]
@baev is there a better way to provide properties for allure-commandline?

**Comment by cherninely** [comment]
@just-boris `Report directory <-Dallure.issues.tracker.pattern=https://st.yandex-team.ru/> not found`

Using this command: `allure generate hermione-allure-results -Dallure.issues.tracker.pattern="https://st.yandex-team.ru/"`

**Comment by just-boris** [comment]
I confirm. The way with `-D` arguments doesn't work. Sorry for misleading information, that I gave you before.

Try to create file `allure.properties` with the following content

```
allure.issues.tracker.pattern="https://st.yandex-team.ru/%s"
```

`%s` is a placeholder that will be replaced with actual issue number.
By default it looks for file in current directory. If you would like to customise file location, use `ALLURE_CONFIG` environment variable.

**Comment by cherninely** [comment]
It worked. Thank you. But without double quotes. 
`allure.issues.tracker.pattern=https://st.yandex-team.ru/%s`

**Comment by j0tunn** [comment]
@just-boris Can I add custom label with link to the test? Or where can I find what labels I can add to test?

**Comment by just-boris** [comment]
@j0tunn 
Yes, you can add any arbitrary label (key, value string pair) for test case. They all will be passed through report generator and then you can use it in report for your purposes.

**Comment by just-boris** [comment]
Well, I think it is time to turn this ticket in proposed api discussion. I'd like to add and properly document convenient methods to add links to bug tracker and test management system.

What do you think about that:

``` js
it('is a sample test', () => {
    allure.testId('123');
    allure.issue('ISSUE-124');
});
```

Then you need to put baseUrls into `allure.properties` file at the root of your project:

```
allure.issues.tracker.pattern=http://my-bugtracker.com/issue/%s
allure.tests.management.pattern=http://my-testmanagement.com/testcase/%s
```

**Comment by cakeinpanic** [comment]
this helps to build local report, but when I am using teamcity plugin, `allure.properties` in the same folder with allure results doesn't help to build correct links

What should I do?

**Comment by just-boris** [comment]
As I do not know anything about teamcity plugin, I'd suggest you to ask anyone around [teamcity plugin](https://github.com/allure-framework/allure-teamcity) project.

**Comment by melsyvolfram** [comment]
If suddenly someone else will look for how to put AllureId in the js code (we use the CodeceptJS framework) - I found this working option:
`const allure = codeceptjs.container.plugins('allure')`
`allure.addLabel('as_id', '123456')`
Source: https://github.com/Tinkoff/Allure.XUnit/issues/25
