### ISSUE TITLE
MarkDown Support

### ISSUE THREAD

**Issue by arif49** [allure-framework/allure-js-commons#18]
Any possible way currently to write description in markdown format so eventually it will be generated like the following,

```
<description type="markdown">
```

**Comment by just-boris** [comment]
Well, this is a reasonable request. Will add it.

@baev: we are going to provide markdown descriptions from all Javascript test frameworks. Are you okay with it?

**Comment by seth2810** [comment]
I added the ability to pass description type as second parameter of method setDescription. I also added a new entity - Description.

**Comment by seth2810** [comment]
@arif49 In 1.2.1 you can use test.setDescription(text, type) to set custom description type.

**Comment by just-boris** [comment]
yes, the issue had been resolved.

See [mocha-example](https://github.com/allure-examples/mocha-allure-example/blob/master/test/webdriver-io.spec.js#L37) to check out how it works
