### ISSUE TITLE
Unexpected endStep

### ISSUE THREAD

**Issue by monolithed** [allure-framework/allure-js-commons#21]
```
19:03:39 allure-js-commons: Unexpected endStep(). There is no any steps running
19:04:49 allure-js-commons: Unexpected endStep(). There is no any steps running
19:07:10 allure-js-commons: Unexpected endStep(). There is no any steps running
19:13:02 allure-js-commons: Unexpected endStep(). There is no any steps running
```

What does it mean?

**Comment by just-boris** [comment]
That means exactly what it says. Your test framework behaves wrong and sends unexpected events.

What test setup (framework, additional libraries) are you using?

**Comment by monolithed** [comment]
> What test setup (framework, additional libraries) are you using? 

[webdriverio](https://github.com/webdriverio/webdriverio) + [wdio-allure-reporter](https://github.com/webdriverio/wdio-allure-reporter)

**Comment by dayanamcc** [comment]
same problem,  how can i says to allure that ignore the hooks ?
example how to said to allure that shoul ignore beforeSuite hook
beforeSuite: function (suite) {
        var clean = require('./src/clean.js')
 },

**Comment by jagannath13** [comment]
same problem after migrating from mocha to jasmine

**Comment by dayanamcc** [comment]
im using:
WebdriverIO 
grunt 
mocha

    "allure-commandline": "^2.0.1",
    "config": "^1.25.1",
    "wdio-allure-reporter": "^0.1.2"

**Comment by criscodex** [comment]
I'm seeing this as well (webdriverIO, mocha, jasmine, wdio-allure-reporter).

**Comment by fgather** [comment]
We see it to with WebdriverIO, jasmine and the wdio-allure-reporter

**Comment by saritanzu** [comment]
See it too in wdio-allure-mocha, when I run all of tests together. And my test suite never ends.

**Comment by ghost** [comment]
Using webdriverio, allure-reporter, and mocha. I was getting the same error/warning message. Turned out to be my test code. I had code outside of a step. Put it inside a step and _voila_, no more error.  Originally, I had this:
```
  5 describe('login screen', function() {
  6   this.timeout(0);
  7   browser.windowHandleMaximize();
  8     
  9   it('should deny access if username is invalid', function() {
 10     let parms = util.readConfig();
 11     // inject bogus username
 12     parms.username = 'HorseWithNoName';
[...]
```
Changed it to this and the message disappeared (I'll put it in a before* hook):
```
  5 describe('login screen', function() {
  6 
  7   it('should deny access if username is invalid', function() {
  8     this.timeout(0);
  9     browser.windowHandleMaximize();
 10 
 11     let parms = util.readConfig();
 12     // inject bogus username
 13     parms.username = 'HorseWithNoName';
 [...]
```
Hope this helps someone.

**Comment by funky17** [comment]
I am getting the same error:
allure-js-commons: Unexpected endStep(). There are no any steps running

I am using before hook in the tests and I need it. Tests look like below:

describe('login', () => {
    before() {
        .....
    }
    it('should sign in', () => {
        ....
    });
});

is there a work around for this?

**Comment by just-boris** [comment]
This issue should be handled by the test framework, that you are using.

**Comment by funky17** [comment]
@just-boris

I am using webdriverio, mocha and wdio-allure-reporter

Any idea how to handle from webdriverio?

**Comment by manvydasu** [comment]
Do you have `disableMochaHooks` set to true?
