### ISSUE TITLE
Correctly adding labels

### ISSUE THREAD

**Issue by matt-mcc1** [allure-framework/allure-js-commons#27]
Hey, great work with this project 

Would you mind showing me the full steps to add labels? I've tried a lot of different ways and unfortunately get errors such as 'addLabel is not a function' etc.  

I appreciate that in the spec file we can call 'allure.addLabel("severity", "trival");  within the Jasmine "it" blocks.

Where do we globally define Allure?  The conf.js file or the spec? Would this just be global.allure = allure; within the onPrepare that contains var AllureReporter = require('jasmine-allure-reporter'); ?

Do I need to declare var runtime = require('allure-js-commons') ?

Many thanks in advance!

**Comment by just-boris** [comment]
Yes, Jasmine adapter, as well as others, provides you a global `allure` object, that you can use to provide additional information out of your tests.

```js
it('is a test with label', () => {
  allure.severity(allure.SEVERITY.TRIVIAL);
});
```

Also note that we have convenient methods for some common labels such as `severity`, `feature` and `story`. It is desribed in the Allure-mocha project, but the API is identical, so you can also rely on that methods: https://github.com/allure-framework/allure-mocha#runtime-api
