### ISSUE TITLE
Change file encoding in case of images

### ISSUE THREAD

**Issue by sharadJay** [allure-framework/allure-js-commons#28]
I am trying to attach screenshots of my test cases and I have raw data response from selenium. I see these files can only be written in base64 format and in allure when [writing files](https://github.com/allure-framework/allure-js-commons/blob/master/writer.js#L11) encoding format is not passed. Can we pass encoding format when adding attachments?

**Comment by just-boris** [comment]
We are accepting `Buffer` as an input value. You can wrap a response into a buffer object on your side

```js
allure.createAttachment('screenshot', Buffer.from(response.value, 'base64'))
```

**Comment by sumeetp4** [comment]
Hey @just-boris , do we need to specify any particular path to save the screenshot?
