### ISSUE TITLE
Attachments and nested BDD describe statements support?

### ISSUE THREAD

**Issue by guiprav** [allure-framework/allure-js-commons#3]
Hi. I'm seriously considering writing a Jasmine reporter for Allure, so I figured I should use allure-js-commons, however it doesn't look like it supports attachments or nested "describes".

I think Mocha supports nested describes too, so that particular change might benefit allure-mocha-reporter too, but does Allure itself even support that?

I need attachments support for adding application screenshots.

I'd like to know how hard would it be to add support for those things and if @just-boris would help me a bit if in case I ran into trouble.

Thanks ;)

**Comment by just-boris** [comment]
Yes we are working on it.
Now we have PR #2 with basic concept

**Comment by just-boris** [comment]
done.
You can provide steps and attachments via the following API: https://github.com/allure-framework/mocha-allure-reporter/blob/master/test/fixtures/simple.spec.js#L3-6

**Comment by just-boris** [comment]
@n2liquid if you are going to create jasmine adapter, you are welcome.
Look at how mocha-repoter is designed. It is just single file https://github.com/allure-framework/mocha-allure-reporter/blob/master/index.js

I guess you can make similar hooks to jasmine. Also, if you want to enrich your test extra information, such as a features or attachments, you should add extra API functions into tests scope. `allure-js-commons` have a special file to it: https://github.com/allure-framework/allure-js-commons/blob/master/runtime.js

If you will have more questions, feel free to create new issue into this repository

**Comment by guiprav** [comment]
Awesome. It's still unclear whether I'll be able to convince my team to use Allure, but if I do, I'll implement the Jasmine adapter. It looks pretty simple indeed. Thanks!

**Comment by just-boris** [comment]
@n2liquid good luck!
