### ISSUE TITLE
Implement custom categories from Allure 2 Beta 6 release

### ISSUE THREAD

**Issue by doppelganger23** [allure-framework/allure-js-commons#31]
It would be very nice if you implement support of broken test statuses and a way to determine them via categories.json, as described in this article: https://qameta.io/blog/2017/03/allure2-beta6/
<img width="688" alt="categories" src="https://user-images.githubusercontent.com/14851966/30273927-d35c57ae-9703-11e7-92c6-a269cf9f6aa6.png">

```
[
  {
    "name": "Ignored tests",
    "messageRegex": ".*ignored.*",
    "matchedStatuses": [ "skipped" ]
  },
  {
    "name": "Infrastructure problems",
    "traceRegex": ".*RuntimeException.*",
    "matchedStatuses": [ "broken", "failed" ]
  },
  {
    "name": "Outdated tests",
    "messageRegex": ".*FileNotFound.*",
    "matchedStatuses": [
      "broken"
    ]
  }
]
```

**Comment by just-boris** [comment]
Hello! I am currently doing some work about migration to Allure 2 API.
It will take some time, for the time being, you can provide `categories.json` yourself put it to `allure-results` folder manually.

**Comment by doppelganger23** [comment]
Thanks!
About broken statuses - I've done some research and figured out that statuses could not be controlled through categories.json (you can only change category for certain status).
In fact, broken statuses are only available if you are using java runner which throws Exceptions, not Errors.
Js test runners (for example Jasmine+Protractor) allways handle that exceptions and throw Errors, so you couldn't get broken test result via allure-js-commons anyway.
Please fix me if I am wrong.

**Comment by just-boris** [comment]
The current package `allure-js-commons` doesn't do any assumptions about statuses. It receives testcase status via `allure.endCase(status)`.

If you have problems with unexpected statuses, please report them to framework adapter that you are using. Currently we officially support two of them:
* Jasmine: https://github.com/allure-framework/allure-jasmine
* Mocha: https://github.com/allure-framework/allure-mocha

Also, a code sample that we can run and see ourselves is necessary for a good bug report.

**Comment by doppelganger23** [comment]
Thanx again!
I have raised an issue on allure-jasmine https://github.com/allure-framework/allure-jasmine/issues/32

**Comment by wluu** [comment]
Hello. Just curious, is allure-js-commons going to be replaced with https://github.com/allure-framework/allure-js?

**Comment by baev** [comment]
As soon as we'll find the person who would like to maintain it. Or later this year just after first Allure 3 milestone will be released
