### ISSUE TITLE
[Improvement] Possibility to add data for all testcases in suite

### ISSUE THREAD

**Issue by cakeinpanic** [allure-framework/allure-js-commons#32]
I have a case: 
before all tests in my suite i log in within some user which is selected randomly
I would like to add this information to all tests of this suite in beforeAll
Something like this:
```
// this whole suite fails
describe("profile test", () => {
  beforeAll(() => {
    allure.setDescription('user is ', randomUser);
    login(radomUser); 
  });
  it("dome testcase", () => {
  });
});
```

And then this description would appear in every test of this suite

**Comment by just-boris** [comment]
There is already another request about it: https://github.com/allure-framework/allure-js-commons/issues/29

For the time being, while this issue is not resolved, you can provide this file yourself. You need to put into `allure-results` (or you custom name) the file `environment.properties` with the `key=value` content.

**Comment by cakeinpanic** [comment]
No, this is not my concern, I want to add _different_ data to suites, not whole environment information.
Look at these suites, in my report i want to see credentials we were logged in in each case of the suite.

```js
const userPetya = {login:'petya', password: 'qwerty'};
const userMasha = {login:'masha', password: 'qwerty'};

function login(user){
    allure.setDescription('user is ', user.login);
    authService.login(user);
}

describe("masha test", () => {
  beforeAll(() => {
        login(userMasha);
  });
  it("masha is a girl", () => {
  });
});

describe("petya", () => {
  beforeAll(() => {
     login(userPetya); 
  });
  it("petya is a boy", () => {
  });
});
```

Seems that this problem can be solved by calling `setDescription` in `beforeEach`, but I think it should be better handled by allure if possible

**Comment by just-boris** [comment]
The current version of Allure model doesn't allow to attach any information to the suite. The source of information is a testcase, suite becomes just a named group of test cases.

@baev how would you fit the request above into Allure 2 model?

**Comment by cakeinpanic** [comment]
I suggest not to store any data in a testsuite, just note that all testcases of this suite should get some data while running.
When test starts, it gets some _common_ data from it's suite if there is one

**Comment by just-boris** [comment]
Then it has nothing to do within `allure-js-commons`. This package aims to be as simple as possible. For this particular case, it can be worked around with a code like the following:

```js
describe("masha test", () => {
  const userInfo = {login:'masha', password: 'qwerty'};

  beforeAll(() => {
    login(userInfo);
  });

  beforeEach(() => {
    allure.description(`User: ${userInfo.login}, pwd: ${userInfo.password}`)
  });

  it("masha is a girl", () => {
    //...
  });
});
```

Or if you would like more generic helper it could look like this

```js
function describeWithUser(title, userInfo, fn) {
  beforeAll(() => login(userInfo));
  beforeEach(() => allure.description(`User: ${userInfo.login}, pwd: ${userInfo.password}`));
  fn();
}

//usage:

describeWithUser('petya', {login:'petya', password: 'qwerty'}, () => {
  it("petya is a boy", () => {
  });
});

describeWithUser('masha', {login:'masha', password: 'qwerty'}, () => {
  it("masha is a girl", () => {
  });
});
```
All tests within a special `describeWithUser` block will have all necessary information.
