### ISSUE TITLE
Missed types

### ISSUE THREAD

**Issue by zaqqaz** [allure-framework/allure-js-commons#37]
it's just FYI :) 

As types definitions are missed for this project, 
I implemented them by myself PR on review now https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25942

**Comment by just-boris** [comment]
Good to hear that!

How are you going to use them in the project? Allure injects API as a global object, so you will need to declare ambient variable in any way. See the issue: https://github.com/allure-framework/allure-jasmine/issues/21

**Comment by zaqqaz** [comment]
@just-boris
`Allure injects API` it depends how you implement that. Allure itself its just a class.
Which we create in the libary (it will `jest-allure`) and in the libary we have 
`declare var allure: Allure;` as it's libary create global allure object, not `allure-js-commons` itself.

**Comment by just-boris** [comment]
ok, I see you point. This totally should work fine.

Good luck you implementing this!

**Comment by zaqqaz** [comment]
@just-boris now you can check it here https://github.com/zaqqaz/jest-allure
