### ISSUE TITLE
Rewrite using TypeScript

### ISSUE THREAD

**Issue by pumano** [allure-framework/allure-js-commons#38]
I would love to rewrite `allure-js-commons` using TypeScript with proper transpilation to es5 for publishing.

**Benefits:**
- better code readability
- better code maintenance
- types
- IDE auto complete

**Comment by baev** [comment]
We already have this done, check this out https://github.com/korobochka/allure2-js-commons
We are going to merge this into main repo as soon as allure 3 was released

**Comment by pumano** [comment]
@baev OK, good!

**Comment by baev** [comment]
@pumano it would be great if you check out the code, all contributions are welcome!
Also you can take a look to https://github.com/korobochka/cucumberjs-allure2-reporter and https://github.com/korobochka/jasmine-allure2-reporter

**Comment by pumano** [comment]
@baev Thanks, I thinking about implementing TypeScript decorators aka `@Step`, `@Title`, and etc (with same behaviour as java allure annotations). I have my own `@Step` decorator and I currently thinking about how to add it to https://github.com/korobochka/allure2-js-commons

**Comment by baev** [comment]
feel free to summon me to review your changes

**Comment by sskorol** [comment]
@baev is https://github.com/korobochka/allure2-js-commons compatible with recent Allure 2 version, or it'll work only with Allure 3?

**Comment by baev** [comment]
> is https://github.com/korobochka/allure2-js-commons compatible with recent Allure 2 version

yes
