### ISSUE TITLE
How to fix "allure-js-commons: Unexpected endStep(). There is no any steps running"?

### ISSUE THREAD

**Issue by naohashizume** [allure-framework/allure-js-commons#44]
Hi, I would like to know how I can fix the following error message.
`allure-js-commons: Unexpected endStep(). There is no any steps running` 

I'm using:
- @wdio/allure-reporter: ^5.16.10
- @wdio/cli: ^5.10.10

All tests are passed without any issue, however I'm still seeing this message when test started running. Please help. Thanks!

**Comment by mrister** [comment]
Seeing this issue also with "@wdio/allure-reporter": "^7.14.1" "webdriverio": "^7.7.8",

allure-js-commons: Unexpected endStep(). There are no any steps running
