### ISSUE TITLE
Ability to add attachments to steps

### ISSUE THREAD

**Issue by ctapobep** [allure-framework/allure-js-commons#5]
While Java implementation is able to add attachments to the steps, JS implementation only allows that for test cases. It's expected that this code adds attachment to the enclosing step:

``` javascript
allure.createStep('enclosing step', function() {
  allure.createAttachent('name', function() {return 'blah'}, 'application/text')();
})();
```

**Comment by just-boris** [comment]
Well, this is a good feature.
Also I think about ability to add attachment without function. Most use-cases doesn't require function wrapper here.

**Comment by just-boris** [comment]
I'll try to do it at the next week

**Comment by just-boris** [comment]
Done, but it a bit unusable until #6 will be implemented too
