### ISSUE TITLE
Archive repo

### ISSUE THREAD

**Issue by vovsemenv** [allure-framework/allure-js-commons#51]
Should we archive this repo and add https://github.com/allure-framework/allure-js link on top of the readme?

**Comment by ebickle** [comment]
The latest version of https://www.npmjs.com/package/allure-js-commons has a transitive vulnerability to `file-type`. If the repository is archived the NPM packages should be as well - there are some upstream consumers of it that might not be realizing they shouldn't be using it any longer.
