### ISSUE TITLE
Provide parameters from test case

### ISSUE THREAD

**Issue by just-boris** [allure-framework/allure-js-commons#8]
Possible api

``` js
it("is a test", function() {
    allure.addArgument("browser", "Chrome")
    allure.addArgument("capabilities", "chrome.latest.mac")
});
```

**Comment by ctapobep** [comment]
Is this a new notion? I remember there were labels in Allure. Where will the arguments be shown?

**Comment by just-boris** [comment]
It is already implemented in java for a long time. Now we have a demand to do it in javascript.

If these parameters exist, they will be shown under test case title: 
![image](https://cloud.githubusercontent.com/assets/812240/11562423/f07fbd2c-99de-11e5-967a-97fac7b5abf8.png)

Also you will be able to set an environment entity. It is key-value list under the failure message.

``` js
allure.addEnvironment("testHost", "http://example.com/")
```

Links in the environment are clickable.

**Comment by just-boris** [comment]
The new methods are described here:
https://github.com/allure-framework/mocha-allure-reporter/blob/master/README.md#runtime-api

I know, that is kinda weird, but now I don't have any another place to keep it.

**Comment by ctapobep** [comment]
You could create a page in allure-common and reference it from the concrete reporters pages. I'd add it to jasmine reporter as well.
