### ISSUE TITLE
endSuite should return XML file path

### ISSUE THREAD

**Issue by georgecrawford** [allure-framework/allure-js-commons#9]
It'd be really nice if `Allure.prototype.endSuite` could return the path generated at https://github.com/allure-framework/allure-js-commons/blob/b31aab566ed04b0a2ec816651a05f16d534879ed/writer.js#L9. As a UUID is used rather than a timestamp, it's hard to see which are the most recent files in that directory. Having them in the test output would be great!

**Comment by just-boris** [comment]
We have discussed it wil @baev and come up with the consideration, that the change would break incapsulation. Also there will be the same issue with attachement files.

But I understand your problem. In mocha-example I have a nice ["pretest" script](https://github.com/allure-examples/mocha-allure-example/blob/master/package.json#L11) to clean up directory before run.

if you want to keep several recent reports, you can configure dynamic `targetDir` option. I tried to do it with mocha-reporter and it worked nice:

```
mocha --reporter mocha-allure-reporter --reporter-options targetDir=results-$(date +%s)
```

I'm getting results in the `results-*` folder.

Does it work for you too?

**Comment by georgecrawford** [comment]
Yeah, that will do. I understand your reasons not to change.
